name: Build and test

on:
  #to manually trigger pipeline
  workflow_dispatch:

  #trigger pipeline on pull request
  pull_request:
    types: [assigned, opened, synchronize, reopened]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      #checkout repo
      - uses: actions/checkout@v2

      #setup node env on the container
      - uses: actions/setup-node@v2
        with:
          node-version: '16'

      #install dependencies, build and test server
      - name: Build and test backend
        working-directory: ./wcag-tool/backend
        run: |
          touch .env
          echo MONGO_URI=${{ secrets.MONGO_URI }} >> .env
          cat .env
          npm ci
          npm run build --if-present
          npm run test
          npm run test:jest

      #install dependencies, build and test client
      - name: Build and test client
        working-directory: ./wcag-tool/chrome-extension
        run: |
          npm ci
          npm run build --if-present
          npm run test
