name: CI pipeline

on:
  #to manually trigger pipeline
  workflow_dispatch:

  #trigger pipeline on pull request
  pull_request:
    types: [assigned, opened, synchronize, reopened]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      #checkout repo
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      #setup node env on the container
      - uses: actions/setup-node@v2
        with:
          node-version: '16'

      #install dependencies, build and test server
      - name: Build and test backend
        working-directory: ./wcag-tool/backend
        run: |
          npm ci
          npm run lint
          npm run build --if-present
          npm test
          
      - name: ESLint checker
          # You may pin to the exact commit or the version.
          # uses: ninosaurus/eslint-check@30ce7263e3f4b0bebc3cc06897bdf4ab8524a424
        uses: ninosaurus/eslint-check@v5.3.1
        with:
            repo-token: ${{ secrets.GITHUB_TOKEN }}           
            custom-directory: ./wcag-tool/backend/
            eslint-config-path: ./wcag-tool/backend/.eslintrc.json

      #install dependencies, build and test client
      - name: Build and test client
        working-directory: ./wcag-tool/chrome-extension
        run: |
          npm ci
          npm run lint
          npm run build --if-present
          npm test

      #sonarCloud analyses
      - name: SonarCloud scan
        uses: sonarsource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
