name: Lint

on:
  #to manually trigger pipeline
  workflow_dispatch:

  #trigger pipeline on pull request
  pull_request:
    types: [assigned, opened, synchronize, reopened]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      #checkout repo
      - uses: actions/checkout@v2

      #setup node env on the container
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
        
      - name: Run eslint on changed files       
        uses: tj-actions/eslint-changed-files@v8
        with:
          token:  ${{ secrets.GITHUB_TOKEN }}
          config_path: ./wcag-tool/backend/.eslintrc.json
    
   
