name: Lint

on:
  #to manually trigger pipeline
  workflow_dispatch:

  #trigger pipeline on pull request
  pull_request:
    types: [assigned, opened, synchronize, reopened]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      #checkout repo
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      #setup node env on the container
      - uses: actions/setup-node@v2
        with:
          node-version: '16'

      #install dependencies server
      - name: Install dependencies for backend
        working-directory: ./wcag-tool/backend
        run: npm ci
        
      - name: Run eslint on changed files
        # You may pin to the exact commit or the version.
        # uses: tj-actions/eslint-changed-files@2373b6d4d792b59076a1c3d5adeb6cb0e0e9476f
        uses: tj-actions/eslint-changed-files@v8
        with:
          token:  ${{ secrets.GITHUB_TOKEN orn }}
          config_path: ./wcag-tool/backend/.eslintrc.json
    
      #install dependencies client
      - name: Install dependencies for client
        working-directory: ./wcag-tool/chrome-extension
        run: npm ci
