name: SonarCloud scan

on:
  #to manually trigger pipeline
  workflow_dispatch:

  #trigger pipeline on pull request
  pull_request:
    types: [assigned, opened, synchronize, reopened]

jobs:
  sonar-scan:
    runs-on: ubuntu-latest

    steps:
      #checkout repo
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      #setup node env on the container
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
     
      #sonarCloud analyses
      - name: SonarCloud scan
        uses: sonarsource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}